meta_product_name: "BlitzLiga"
meta_title: "Blitzliga - Moscow's six-a-side football league"
meta_description: "Players from around the world playing Sunday morning football in Moscow since 2012"
meta_image: "logo.png"                       # should exist in `app/assets/images/`
twitter_account: "@blitzliga"   # required for Twitter Cards
